### ISSUE TITLE
Msg Editor for japanese files

### ISSUE THREAD

**Issue by cicciodiemme** [MugenAttack/Xenoverse-Msg-File-Editor#1]
Hi, MugenAttack! First of all, I want to thank you for creating this very useful tool!
I wanted to ask you something. I have some japanese Xenoverse 2 msg files and, as bizarre as it may seem, I need to check the text inside of them.
The problem is that the editor only shows the first "letter" of each sentence/name.
https://i.imgur.com/OKKJMIh.png
Is there anyway to fix this bug? I'm leaving a sample file here.
[proper_noun_character_name_ja.zip](https://github.com/MugenAttack/Xenoverse-Msg-File-Editor/files/1787851/proper_noun_character_name_ja.zip)

Thanks in advance!

**Comment by MugenAttack** [comment]
tested it with the msg editor in xv2lib same result. also eternity's tool genser has the same result.

sorry for late response. never noticed the notifications. XD

also going to use the file to test if japanese language is possible with pc version.

**Comment by MugenAttack** [comment]
the msg file has a different setup than whats in the pc version so its not supported in the tools.

**Comment by MugenAttack** [comment]
its not that hard to add support for it though

**Comment by cicciodiemme** [comment]
I didn't mention that I extracted the file from the Switch version of the game (since in Japan, it has never been released on PC). Do you think it has something to do with that? I unfortunately forgot to test the editor with Switch english files...
Anyway, I hope there may be a solution, one day!

**Comment by MugenAttack** [comment]
its actually easy to add in.  text is read differently that's the only difference.

**Comment by MugenAttack** [comment]
https://github.com/MugenAttack/XV2Lib/releases/tag/MSG-v1.2

this should load the files.  

also pc version doesn't support japanese text. did a test with the conversion option.

**Comment by cicciodiemme** [comment]
I cannot thank you enough for this! You did a great job! :)

**Comment by XV2jp** [comment]
Hi MugenAttack I also face this problem I succeeded in displaying Japanese However
https://imgur.com/a/UNyjauu
Subtitle text was tested like this
Japanese on the screen is manual input, and the right side of the tool is CS text
Oddly enough, tools and games are discharging the same results
Is there a solution A sample file
https://github.com/MugenAttack/Xenoverse-Msg-File-Editor/files/3598194/cp_qs_cep00_jp.zip
